version: '3.8'
services:
  dev:
    build: .
    image: my-ping-dev
    container_name: ping-dev
    working_dir: /app
    volumes:
      - ../src:/app/src
      - ../include:/app/include
      - ../Makefile:/app/Makefile
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    privileged: true
